export const outbox_commands = {
  draft_send: "draft_send",
  draft_save: "draft_save",
  draft_delete: "draft_delete",
  send_email: "send_email",
  delete_email: "delete_email",
  label_update: "label_update",
  label_batch: "label_batch",
  mark_as_read: "mark_as_read",
  mark_as_unread: "mark_as_unread",
  mark_as_spam: "mark_as_spam",
  mark_as_phishing: "mark_as_phishing",
  move_to_archive: "move_to_archive",
  move_to_inbox: "move_to_inbox",
  untrash: "untrash",
  block_sender: "block_sender",
  toggle_important: "toggle_important",
  toggle_starred: "toggle_starred",
} as const;
