import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { accounts } from "./accounts";
import { threads } from "./threads";

export const emails = sqliteTable("emails", {
  id: text("id").primaryKey(),
  provider: text("provider").notNull(),
  account_id: text("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }),
  thread_id: text("thread_id").references(() => threads.id),
  message_id: text("message_id"),
  subject: text("subject"),
  from_name: text("from_name"),
  from_address: text("from_address"),
  to: text("to"),
  cc: text("cc"),
  bcc: text("bcc"),
  reply_to: text("reply_to"),
  reply_to_address: text("reply_to_address"),
  labels: text("labels"),
  classification_labels: text("classification_labels"),
  history_id: text("history_id"),
  size_estimate: integer("size_estimate"),
  internal_date: text("internal_date"),
  cid_refs_fetched: integer("cid_refs_fetched").default(0),
  body_text: text("body_text"),
  body_html: text("body_html"),
  mail_cached_at: text("mail_cached_at"),
  image_dimensions: text("image_dimensions"),
  images_measured: integer("images_measured").default(0),
  snippet: text("snippet"),
  folder: text("folder").notNull().default("inbox"),
  is_read: integer("is_read").default(0),
  is_starred: integer("is_starred").default(0),
  is_flagged: integer("is_flagged").default(0),
  is_phishing: integer("is_phishing").default(0),
  received_at: text("received_at"),
  sent_at: text("sent_at"),
  created_at: text("created_at").default("datetime('now')"),
  updated_at: text("updated_at").default("datetime('now')"),
  synced_at: text("synced_at"),
  original_email_id: text("original_email_id"),
  draft_mode: text("draft_mode"),
  gmail_draft_id: text("gmail_draft_id"),
  local_draft_id: text("local_draft_id"),
  quote_text: text("quote_text"),
  draft_version: integer("draft_version").notNull().default(1),
});
